name: Create Assets

on:
  release:
    types: [published]

env:
  PROGRAM: gitit
  DIR: gitit
  EXTRA_ASSETS: data LICENSE YUI-LICENSE
  PROXY: unix-proxy.sh
  HIDDEN_BIN: gitit-bin

jobs:
  create-assets:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        with-plugins: [true, false]

    steps:
    - uses: actions/checkout@v2

    - name: Build the project
      run: stack build --ghc-options=-rtsopts
      if: ${{ matrix.with-plugins }}

    - name: Build the project, without plugins
      run: stack build --ghc-options=-rtsopts --flag gitit:plugins
      if: ${{ !matrix.with-plugins }}

      # This also renames the program name and instead injects a proxy shell
      # script that takes care of overriding the cabal inserted paths before
      # running the actual program

    - name: Prepare directory
      run: |
        mv `stack exec -- which $PROGRAM` $HIDDEN_BIN
        mkdir $DIR
        mv $PROXY $DIR/$PROGRAM

    - name: Tar the directory
      run: |
        mv $HIDDEN_BIN $EXTRA_ASSETS plugins $DIR
        tar -cavf $DIR.tar.gz $DIR
      if: ${{ matrix.with-plugins }}

    - name: Tar the directory
      run: |
        mv $HIDDEN_BIN $EXTRA_ASSETS $DIR
        tar -cavf program.tar.gz $DIR
      if: ${{ !matrix.with-plugins }}

    - name: Upload assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./gitit.tar.gz
        asset_name: gitit-${{ runner.os }}.tar.gz
        asset_content_type: application/tar.gz
      if: ${{ matrix.with-plugins }}

    - name: Upload assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./gitit.tar.gz
        asset_name: gitit-${{ runner.os }}-noplugins.tar.gz
        asset_content_type: application/tar.gz
      if: ${{ !matrix.with-plugins }}
